### PR TITLE
Update profiling and gpu conda env documentation

### LINKED ISSUE #53: Update profiling docs
Refresh profiling docs, specifically, add MPI + GPU example to profiling docs.

### PR DESCRIPTION
**Pull request by dmargala**
This PR updates the profiling documentation (resolves #53). I've added instructions for profiling spex using mpi + gpu. It looks like some of the other existing instructions are also out of date so I will update those as well.

### CODE REVIEW

**Comment by dmargala** [comment]
I also updated the "how to build gpu conda env" instructions (resolves #52)

**Review by lastephey — CHANGES_REQUESTED** [review]
Thanks Daniel. It looks good. Can you please add a section that shows the typical multinode configuration you are using on both corigpu and dgx?

**Comment by dmargala** [comment]
For typical benchmarking, I am just using one node with 4 gpus. I will add another section with instructions that typical configuration on corigpu and dgx. 

Multinode is usually just a matter of changing the number of requested nodes in the salloc/sbatch setting.

**Comment by dmargala** [comment]
I added instructions for build a conda env on dgx (unfortunately openmpi is not built for the latest cuda there, it's on the dgx todo and should be done in the next few weeks.)

I also added another doc with configurations for running typical single frame and 30 frame benchmarks.

**Review by lastephey — APPROVED** [review]
Thanks for this additional information.

**Comment by lastephey** [comment]
LGTM, you can merge when you're ready. Thanks for the additional details.

**Pull request merged**
